# This workflow will build the project on a pull request when
# the lable 'trigger-pr-builder' is added.
# Uses:
#   OS: ubuntu-latest
#   JDK: Adopt JDK 11

name: PR Builder

on:
  pull_request:
    types: [ labeled ]
    branches: [ main, master ]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx4g -Xms1g -Dmaven.artifact.threads=20

jobs:
  build:
    if: ${{github.event.label.name == 'trigger-pr-builder' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Adopt JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build init
        run: |
          echo "CURRENT_MONTH=$(date +%Y-%m)" >> ${GITHUB_ENV}
      - name: Build with Maven
        run: mvn -T 1C clean install -U -B
      - name: Delete SNAPSHOT artifacts
        run: find ~/.m2/repository/ -name "*-SNAPSHOT" -type d -print -prune -exec rm -r {} +
